"""cambiando el backref

Revision ID: 1a97f87d9cb4
Revises: 2f2091917a3e
Create Date: 2025-12-29 13:22:13.327966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a97f87d9cb4'
down_revision = '2f2091917a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
