"""eliminando columna direccion de pedidos y usuario

Revision ID: 2f2091917a3e
Revises: a9cf085b5e85
Create Date: 2025-12-23 12:16:53.303043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2091917a3e'
down_revision = 'a9cf085b5e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalles_pedidos_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalles_pedidos_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalles_pedidos_ibfk_1'), 'pedidos', ['id_pedido'], ['id'])
        batch_op.create_foreign_key(batch_op.f('detalles_pedidos_ibfk_2'), 'productos', ['id_producto'], ['id'])

    # ### end Alembic commands ###
