"""agregando columnas a db pedidos

Revision ID: 9efdc3bae66a
Revises: d090fdfe655c
Create Date: 2025-12-21 17:47:08.268758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9efdc3bae66a'
down_revision = 'd090fdfe655c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito_productos')
    op.drop_table('carritos')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_producto', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_producto')

    op.create_table('carritos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='carritos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carrito_productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('carrito_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], name=op.f('carrito_productos_ibfk_1')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('carrito_productos_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
