"""agregando col a producto

Revision ID: d090fdfe655c
Revises: b03489aa3ab4
Create Date: 2025-11-28 13:07:31.264502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd090fdfe655c'
down_revision = 'b03489aa3ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')
        batch_op.drop_column('precio')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
