"""editando tabla pedidos

Revision ID: faf51df6b367
Revises: 1a97f87d9cb4
Create Date: 2025-12-29 14:15:43.853389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faf51df6b367'
down_revision = '1a97f87d9cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
